name: Build The Exe 

on:
  push:
    branches: [ master ]

jobs:
  build_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test Build Python Exe
        uses: eric2788/pyinstaller-build@master
        with:
          main: main
          artifact: Play_TicTaeToe_AI
          no-console: true
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: executable
          path: dist